# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'spvchannels' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for spvchannels
  pod 'Alamofire', '<= 4.9.0'
  pod 'SwiftLint'
  pod 'Sodium'

  target 'spvchannelsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'spvchannelsUITests' do
    # Pods for testing
  end

end
