# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'spvchannels' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for spvchannels
  pod 'SwiftLint'
  pod 'Sodium'
  pod 'Firebase/Messaging'

  target 'spvchannelsTests' do
    inherit! :search_paths
    pod 'Sodium'
    pod 'Firebase/Messaging'
  end

end
